# Generated by Django 3.0.6 on 2020-06-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200510_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
